### PR TITLE
Fix send all L-BTC behavior

### LINKED ISSUE #438: Send All L-BTC should deduct fee from recipient output
related to #436 

`wallet/send/choose-fee.tsx` should handle Send ALL L-BTC case correctly.
Moreover, "retry" button is not working when an error happens.

https://github.com/vulpemventures/marina/pull/436#issuecomment-1470539558

### PR DESCRIPTION
**Pull request by louisinger**
This PR adds a new `createSendAllPset` method to `PsetBuilder` class. It lets to handle correctly the SEND ALL behavior in `wallet/send/choose-fee`.

it also adds receive & send Playwright tests.

it closes #438 

@tiero @bordalix please review

### CODE REVIEW

**Review by tiero — CHANGES_REQUESTED** [review]
CI fails

File: src/domain/pset.ts [hunk 1]
```diff
@@ -13,14 +18,15 @@ import {
...
+import { computeBalances } from './transaction';
 
-function estimateScriptSigSize(type: ScriptType): number {
+function estimateScriptSigSize(type: address.ScriptType): number {
   switch (type) {
-    case ScriptType.P2Pkh:
+    case address.ScriptType.P2Pkh:
       return 108;
-    case (ScriptType.P2Sh, ScriptType.P2Wsh):
+    case (address.ScriptType.P2Sh, address.ScriptType.P2Wsh):
```
Comment (bordalix) [inline src/domain/pset.ts:27]: You have `address.ScriptType.P2Wsh` repeated and I didn't knew this syntax for the case clause 😄 

Maybe we should go for a more conservative approach?

```suggestion
    case address.ScriptType.P2Pkh:
      return 108;
    case address.ScriptType.P2Sh:
      return 35;
    case address.ScriptType.P2Wsh:
    case address.ScriptType.P2Tr:
    case address.ScriptType.P2Wpkh:
      return 1;
```

File: src/extension/components/address-amount-form.tsx [hunk 2]
```diff
@@ -94,7 +94,7 @@ const BaseForm = (props: FormProps & FormikProps<FormValues>) => {
   return (
     <form onSubmit={handleSubmit} className="mt-8">
       <p className="mb-2 text-base font-medium text-left">Address</p>
-      <Input {...props} name="address" placeholder="" type="text" value={values.address} />
+      <Input {...props} name="address" placeholder="lq1..." type="text" value={values.address} />
```
Comment (bordalix) [inline src/extension/components/address-amount-form.tsx:97]: NIT: make the placeholder dependent of the network

File: src/domain/pset.ts (hunk 1 above)
Comment (louisinger) [reply src/domain/pset.ts]: Commited :heavy_check_mark: , just P2WSH must return 35

File: src/domain/pset.ts
Comment (bordalix) [inline src/domain/pset.ts:1]: Ups, my bad, my suggestion was only changing one line, now the code is weird 🙏 

@louisinger

Comment (louisinger) [reply src/domain/pset.ts:1]: yeah don't worry, I'm pushing a fix

File: src/domain/pset.ts [hunk 3]
```diff
@@ -13,14 +18,22 @@ import {
 } from '../application/account';
 import type { WalletRepository, AppRepository, TaxiRepository } from './repository';
 import type { CoinSelection } from './transaction';
+import { computeBalances } from './transaction';
 
-function estimateScriptSigSize(type: ScriptType): number {
+function estimateScriptSigSize(type: address.ScriptType): number {
   switch (type) {
```
Comment (bordalix) [inline src/domain/pset.ts:24]: Unable to make suggestion on multiple lines since there are deleted lines in between.

The final code for the switch case should be:

```
  switch (type) {
    case address.ScriptType.P2Pkh:
      return 108;
    case address.ScriptType.P2Sh:
      return 35;
    case address.ScriptType.P2Wsh:
    case address.ScriptType.P2Tr:
    case address.ScriptType.P2Wpkh:
      return 1;
    default:
      return 0;
  }

**Comment by bordalix** [comment]
NIT: maybe on this screen show the amount minus the fee?

Screenshot 2023-03-21 at 12 07 06

**Review by bordalix — APPROVED** [review]
