### PR TITLE
Fix Self-transfer tx and `goBack` router crash

### LINKED ISSUE #126: Transactions: Add specific labelling for Self Transfer

### PR DESCRIPTION
**Pull request by louisinger**
TLDR
* Display Self-Transfer tx (as a "deposit" of zero) in tx history + add a `TxType`.
* Fix some buggish behaviors of the router in `SettingsMenu`.

it closes #126 

@tiero please review

### CODE REVIEW

**Comment by tiero** [comment]
It closes #126 ? If yes add to PR description

File: src/presentation/settings/menu-settings.tsx [hunk 1]
```diff
@@ -16,7 +17,11 @@ const SettingsMenuSettings: React.FC = () => {
   const handleDeepRestorer = () => history.push(SETTINGS_DEEP_RESTORER_ROUTE);
 
   return (
-    <ShellPopUp className="h-popupContent" currentPage="Settings">
+    <ShellPopUp
+      className="h-popupContent"
+      currentPage="Settings"
+      backBtnCb={() => history.push(DEFAULT_ROUTE)}
```
Comment (tiero) [inline src/presentation/settings/menu-settings.tsx:23]: why not `goBack`? this will add a new route to the stack

File: src/presentation/wallet/send/end-of-flow.tsx [hunk 2]
```diff
@@ -51,15 +51,15 @@ const EndOfFlow: React.FC<EndOfFlowProps> = ({
...
       });
-    } catch (error) {
+    } catch (error: any) {
       return history.push({
         pathname: SEND_PAYMENT_ERROR_ROUTE,
         state: {
           tx: tx,
-          error: error.message,
-        },
+          error: error?.message || error
```
Comment (tiero) [inline src/presentation/wallet/send/end-of-flow.tsx]: If we expect a string (error.message), what are probabilities error is a string already, most likely is an object or undefined? Would be better to JSON.stringify?

File: src/presentation/wallet/transactions/index.tsx [hunk 3]
```diff
@@ -45,10 +46,10 @@ const TransactionsView: React.FC<TransactionsProps> = ({
   const { state } = useLocation<LocationState>();
   const dispatch = useDispatch<ProxyStoreDispatch>();
 
-  const assetImgPath =
+  const getAssetImgPath = () =>
     network === 'regtest'
-      ? imgPathMapRegtest[state.assetTicker] ?? imgPathMapRegtest['']
-      : imgPathMapMainnet[state.assetHash] ?? imgPathMapMainnet[''];
+      ? imgPathMapRegtest[state.assetTicker ?? networks.regtest.assetHash] ?? imgPathMapRegtest['']
+      : imgPathMapMainnet[state.assetHash ?? networks.regtest.assetHash] ?? imgPathMapMainnet[''];
```
Comment (tiero) [inline src/presentation/wallet/transactions/index.tsx:52]: Shoudldnt be `networks.liquid` ?

File: src/presentation/settings/menu-settings.tsx (hunk 1 above)
Comment (louisinger) [reply src/presentation/settings/menu-settings.tsx:23]: to be consistent with the others screens (we also push to home in `Send` and `Receive`). We use  `goback` in all sub-menus (Settings for instance).
