### PR TITLE
Bug fix and improvement on marina events

### LINKED ISSUE #377: NEW_UTXO and SPENT_UTXO  events should be fired for all accounts and return the accountID
```ts
marina.on('NEW_UTXO', (utxo, accountId) => {})
```

### PR DESCRIPTION
**Pull request by bordalix**
Closes #377

**Bug fixes:**

- fix bug where only the main account was emitting events on `NEW_TX`, `NEW_UTXO` and `SPENT_UTXO`

**Improvements:**

- marina events (see list above) now returns the accountID in the payload

**Breaking changes (marina events):**

- `marina.on('NEW_TX', (tx) => {})` is now `marina.on('NEW_TX', ({ tx, accountID }) => {})`
- `marina.on('NEW_UTXO', (utxo) => {})` is now `marina.on('NEW_UTXO', ({ utxo, accountID }) => {})`
- `marina.on('SPENT_UTXO', (utxo) => {})` is now `marina.on('SPENT_UTXO', ({ utxo, accountID }) => {})`

**Worth mentioning:**

- adds accountID to console.debug when reporting utxos fetched from explorer

@tiero @louisinger please review.

### CODE REVIEW

**Comment by tiero** [comment]
If we pass an additional parameter, instead of changing it to be an object, we should be able to make it not breaking change?

`marina.on('NEW_TX', (tx, accountID?) => {})`

**Comment by bordalix** [comment]
>  If we pass an additional parameter, instead of changing it to be an object, we should be able to make it not breaking change?
> 
> `marina.on('NEW_TX', (tx, accountID?) => {})`

@louisinger help me out here please, but I think this will implicate a profound change on Marina.
Today, the payload for the events is passed between components as a single object (which gets stringified).
@tiero what you ask for would imply to have multiple objects being passed through.

**Comment by bordalix** [comment]
@tiero to avoid more breaking changes, all payloads should be on the form `{ network }` instead of `network`.
This way we can add more attributes without breaking previous code.

**Comment by tiero** [comment]
Agreed. I don't see any other way.

I woudl eventually make a typed interface: 

```ts
interface MarinaEvent {
  accountID: string,
  payload: any
}
```

**Comment by louisinger** [comment]
> If we pass an additional parameter, instead of changing it to be an object, we should be able to make it not breaking change?
> 
> `marina.on('NEW_TX', (tx, accountID?) => {})`

it means update the [MarinaProvider interface](https://github.com/vulpemventures/marina-provider/blob/master/src/provider.ts#L36). 

But anyway not sure how marina background broker can handle this. if user has passed a 1-param func previously, `func(a, undefined)` statement will throw an error anyway. I personally prefer passing an object like joao proposes...

PS: the only way to avoid breaking changes is to return the accountID **inside the current payload**, so in NEW_UTXO we return `{ ...utxo, accountID }` instead of `utxo`. The drawback is `utxo` type don't have the accountID member so it's a kind of "hidden" member from a TS point of view.

PPS: note that due to `payload` typing which depends on the event type, the "breaking change" is a silent one -> it means that linter and TS checks won't see the error (even if a good code should check the type returned by marina)

File: src/application/utils/marina-event.ts [hunk 1]
```diff
@@ -7,25 +7,26 @@ export interface MarinaEvent<P extends any> {
   payload: P;
 }
 
-export type NewUtxoMarinaEvent = MarinaEvent<UnblindedOutput>;
-export type SpentUtxoMarinaEvent = MarinaEvent<Outpoint>;
-export type NewTxMarinaEvent = MarinaEvent<TxDisplayInterface>;
+export type NewUtxoMarinaEvent = MarinaEvent<{ utxo: UnblindedOutput; accountID: string }>;
+export type SpentUtxoMarinaEvent = MarinaEvent<{ utxo: Outpoint; accountID: string }>;
```
Comment (louisinger) [inline src/application/utils/marina-event.ts:11]: nit: I would replace `Outpoint` by `UnblindedOutput` (we pass the whole utxo so user will be able to access all members)

**Review by louisinger — APPROVED** [review]
utACK

**Comment by bordalix** [comment]
Final merge was:

```typescript
interface MarinaEvent {
    accountID?: string
    data: any
}
```

With **data** type depending on event type:

```typescript
marina.on('NEW_TX', ({ accountID, data }) => {}) // data: Transaction
marina.on('NEW_UTXO', ({ accountID, data }) => {}) // data: UnblindedOutput
marina.on('SPENT_UTXO', ({ accountID, data }) => {}) // data: UnblindedOutput
marina.on('ENABLED', ({ data }) => {}) // data: { hostname: string; network: NetworkString }
marina.on('DISABLED', ({ data }) => {}) // data: { hostname: string; network: NetworkString }
marina.on('NETWORK', ({ data }) => {}) // data: NetworkString
```

Updated on https://docs.vulpem.com/marina/api/#marina-events
