### PR TITLE
fixes bug when going back on send address and amount selection

### LINKED ISSUE #379: Bug when going back from send / address and amount
When you click Send, choose the asset and then go back, it works.
When you choose the asset, click Send and then go back, you get a blank screen. 

https://user-images.githubusercontent.com/9318412/185416328-21a4d71a-1a33-462a-951d-1f023af9f50b.mov

### PR DESCRIPTION
**Pull request by bordalix**
closes #379 

@tiero please review

### CODE REVIEW

File: src/presentation/wallet/send/address-amount.tsx [hunk 1]
```diff
@@ -33,7 +34,7 @@ const AddressAmountView: React.FC<AddressAmountProps> = ({
 
   const handleBackBtn = async () => {
     await dispatch(flushPendingTx()).catch(console.error);
-    history.goBack();
+    history.push(DEFAULT_ROUTE);
```
Comment (tiero) [inline src/presentation/wallet/send/address-amount.tsx:37]: replace? otherwise will add more screen on the stack

Comment (bordalix) [reply src/presentation/wallet/send/address-amount.tsx]: resolved by [ba968e7](https://github.com/vulpemventures/marina/pull/380/commits/ba968e7c5069842b8f82a96921945aa6bdf3d7d1)
