### PR TITLE
naming fix + select only spendableByMarina accounts in UI

### LINKED ISSUE #374: UI and marina.sendTransaction should show & use ONLY auto-spendable coins

### PR DESCRIPTION
**Pull request by louisinger**
* HOTFIX: "CustomScriptData.covenantDescriptors" renamed into "contractTemplate" (has been renamed in former PR but some parts of the code still use the empty "covenantDescriptors" field).
* UI selects only the accounts spendable by marina UI (for balances, utxos and transactions). it closes #374 

@tiero please review

### CODE REVIEW

File: src/application/redux/actions/wallet.ts [hunk 1]
```diff
@@ -50,14 +50,10 @@ export function setIsSpendableByMarina(accountID: AccountID, isSpendableByMarina
...
-export function setCustomScriptTemplate(
-  accountID: AccountID,
-  template: string,
-  changeTemplate?: string
-): AnyAction {
+export function setCustomScriptTemplate(accountID: AccountID, template: string): AnyAction {
   return {
     type: SET_CS_ACCOUNT_TEMPLATE,
-    payload: { accountID, template, changeTemplate },
+    payload: { accountID, template },
```
Comment (tiero) [inline src/application/redux/actions/wallet.ts:56]: why we removing changeTemplate?

File: src/application/utils/constants.ts [hunk 2]
```diff
@@ -43,6 +43,8 @@ featuredAssetsMap.set(featuredAssets.lcad.mainnet, getLocalImagePath('lcad.png')
 featuredAssetsMap.set(featuredAssets.lcad.testnet, getLocalImagePath('lcad.png'));
 featuredAssetsMap.set(featuredAssets.fusd.testnet, getLocalImagePath('fusd.png'));
 
+export const FEATURES_ASSETS = Array.from(featuredAssetsMap.keys());
```
Comment (tiero) [inline src/application/utils/constants.ts:46]:
```suggestion
export const FEATURED_ASSETS = Array.from(featuredAssetsMap.keys());
```

File: src/presentation/utils/sort.ts [hunk 3]
```diff
@@ -1,3 +1,4 @@
+import { FEATURES_ASSETS } from '../../application/utils/constants';
```
Comment (bordalix) [inline src/presentation/utils/sort.ts:1]:
```suggestion
import { FEATURED_ASSETS } from '../../application/utils/constants';
```

File: src/presentation/utils/sort.ts [hunk 4]
```diff
@@ -12,22 +13,19 @@ export function sortAssets(
...
-    for (const asset of assets) {
-      if (ticker === asset.ticker) {
-        featuredAssets.push(asset);
-      }
-      if (asset.ticker === newAssetTicker) {
-        newAsset = asset;
-      }
+  const remainingAssets = [];
+  for (const asset of assets) {
+    if (FEATURES_ASSETS.includes(asset.assetHash)) {
```
Comment (bordalix) [inline src/presentation/utils/sort.ts:19]:
```suggestion
    if (FEATURED_ASSETS.includes(asset.assetHash)) {
```

File: src/application/redux/actions/wallet.ts (hunk 1 above)
Comment (tiero) [reply src/application/redux/actions/wallet.ts:56]: @louisinger

Comment (tiero) [reply src/application/redux/actions/wallet.ts:56]: `importTemplate(template: Template, changeTemplate?: Template)`

Comment (louisinger) [reply src/application/redux/actions/wallet.ts:56]: PR https://github.com/vulpemventures/marina/pull/366 removed it

Comment (tiero) [reply src/application/redux/actions/wallet.ts:56]: the description of the PR is not relevant, importTemplate still have the changeTemplate param,look in master

Comment (tiero) [reply src/application/redux/actions/wallet.ts:56]: cc/ @louisinger

Comment (louisinger) [reply src/application/redux/actions/wallet.ts:56]: yeah, `importTemplate` from marina provider defines a changeTemplate parameter but the the PR 366 [removed it from reducer](https://github.com/vulpemventures/marina/pull/366/files#diff-6e5548d2c1bf7cbcf1316da62161e63b60d2cde3fda5743456318ad2e2b0cf04L86) (from CustomScriptAccountData, and do not handle it anymore in CustomScriptIdentity). I've just removed it from the action payload because the reducer never use it

Comment (tiero) [reply src/application/redux/actions/wallet.ts:56]: ok, this seems an error then! 

if you follow the discussion, we actually agreed that is needed to have a different template for change.

If I switch to a custom account with `useAccount`, What will happen to call `getNextChangeAddress`? which kind of address will be returned and from which account?
